import type { QuotationLineItemRecord } from '../../modules/quotation/domain/repositories/quotation-line-item.repository';
import type { QuotationRecord } from '../../modules/quotation/domain/repositories/quotation.repository';

export function buildQuotationPdfLines(input: {
  tenantName: string;
  quotation: QuotationRecord;
  lineItems: QuotationLineItemRecord[];
}): string[] {
  const { tenantName, quotation, lineItems } = input;
  const formatMoney = (amount: number): string =>
    `${quotation.currency} ${amount.toFixed(2)}`;

  const lines = [
    '========================================',
    `  ${tenantName.toUpperCase()}`,
    '  QUOTATION',
    '========================================',
    '',
    `No. ${quotation.quotationNumber} (Rev ${quotation.revisionNumber})`,
    `Status: ${quotation.status}`,
    '',
  ];

  if (quotation.eventType) {
    lines.push(`Event: ${quotation.eventType}`);
  }
  if (quotation.venue) {
    lines.push(`Venue: ${quotation.venue}`);
  }
  if (quotation.validUntil) {
    lines.push(
      `Valid until: ${quotation.validUntil.toISOString().slice(0, 10)}`,
    );
  }

  lines.push('', 'Line items', '----------------------------------------');

  for (const item of lineItems) {
    const lineTotal = item.quantity * item.unitPrice;
    lines.push(
      `${item.description}`,
      `  Qty ${item.quantity} x ${formatMoney(item.unitPrice)} = ${formatMoney(lineTotal)}`,
    );
  }

  lines.push(
    '----------------------------------------',
    `Subtotal:     ${formatMoney(quotation.subtotalAmount)}`,
    `Discount:     ${formatMoney(quotation.discountAmount)}`,
    `Tax (GST):    ${formatMoney(quotation.taxAmount)}`,
    `Total:        ${formatMoney(quotation.totalAmount)}`,
  );

  if (quotation.terms) {
    lines.push('', 'Terms', quotation.terms.slice(0, 500));
  }

  lines.push(
    '',
    '----------------------------------------',
    `Thank you for choosing ${tenantName}.`,
    'This document was generated by Event OS.',
  );

  return lines;
}
